Education_platform/Education_platform/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls import url
from django.views.static import serve

import xadmin
from django.views.generic import TemplateView
from users import views
from users.views import ActiveUserView, ResetView, ForgetPwdView, ModifyPwdView, LogoutView, LoginUnsafeView
from oragnization.views import OrgView

urlpatterns = [
    path('^login/', LoginUnsafeView.as_view(), name='login'),
    path('xadmin/', xadmin.site.urls),
    # path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('', views.IndexView.as_view(), name='index'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('captcha/', include('captcha.urls')),
    re_path('active/(?P<active_code>.*)/', ActiveUserView.as_view(), name='user_active'),
    re_path('reset_pwd/(?P<active_code>.*)/', ResetView.as_view(), name='user_reset_pwd'),
    path('forget/', ForgetPwdView.as_view(), name='forget_pwd'),
    path('modify_pwd/', ModifyPwdView.as_view(), name='modify_pwd'),
    # path('org_list/', OrgView.as_view(), name='org_list'),
    path("org/", include('oragnization.urls', namespace="org")),
    path("course/", include('course.urls', namespace="course")),
    path("users/", include('users.urls', namespace="users")),
    re_path(r'^media/(?P<path>.*)', serve, {"document_root": settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)', serve, {"document_root": settings.STATIC_ROOT}),
]

handler404 = 'users.views.page_not_found'
handler500 = 'users.views.page_error'

Education_platform/apps/course/urls.py
# -*- encoding:utf-8 -*-
# Author:Alano
from django.urls import path, re_path
from .views import CourseListView, CourseDetailView, CourseInfoView, CommentsView, AddCommentsView, VideoPlayView

# 要写上app的名字
app_name = "course"

urlpatterns = [
    path('list/',CourseListView.as_view(), name='course_list'),
    re_path('course/(?P<course_id>\d+)/', CourseDetailView.as_view(), name="course_detail"),
    re_path('info/(?P<course_id>\d+)/', CourseInfoView.as_view(), name="course_info"),
    re_path('comment/(?P<course_id>\d+)/', CommentsView.as_view(), name="course_comments"),
    path('add_comment/', AddCommentsView.as_view(), name="add_comment"),
    re_path('video/(?P<video_id>\d+)/', VideoPlayView.as_view(), name="course_video"),

]

Education_platform/apps/oragnization/urls.py
# -*- encoding:utf-8 -*-
# Author:Alano

from oragnization.views import OrgView, AddUserAskView, OrgHomeView, OrgCourseView, OrgDescView, OrgTeacherView, \
    AddFavView, TeacherListView, TeacherDetailView
from django.urls import path, re_path

# App_name
app_name = "organization"

urlpatterns = [
    path('list/', OrgView.as_view(), name='org_list'),
    path('add_ask/', AddUserAskView.as_view(), name="add_ask"),
    re_path('home/(?P<org_id>\d+)/', OrgHomeView.as_view(), name='org_home'),
    re_path('course/(?P<org_id>\d+)/', OrgCourseView.as_view(), name="org_course"),
    re_path('desc/(?P<org_id>\d+)/', OrgDescView.as_view(), name="org_desc"),
    re_path('teacher/(?P<org_id>\d+)/', OrgTeacherView.as_view(), name="org_teacher"),
    path('add_fav/', AddFavView.as_view(), name="add_fav"),
    re_path('teacher/list/', TeacherListView.as_view(), name="teacher_list"),
    re_path('teacher/detail/(?P<teacher_id>\d+)/', TeacherDetailView.as_view(), name="teacher_detail"),
]

Education_platform/apps/users/urls.py
# -*- encoding:utf-8 -*-
# Author:Alano
from django.urls import path, include, re_path
from .views import UserinfoView, UploadImageView, UpdatePwdView, SendEmailCodeView, UpdateEmailView, MyCourseView, MyFavOrgView, MyFavTeacherView, MyFavCourseView, MyMessageView

app_name = 'users'

urlpatterns = [
    # 用户信息
    path("info/", UserinfoView.as_view(), name='user_info'),
    # 用户图像上传
    path("image/upload", UploadImageView.as_view(),name='image_upload'),
    # 用户个人中心修改密码
    path("update_pwd/", UpdatePwdView.as_view(), name='update_pwd'),
    # 发送邮箱验证码
    path("sendemail_code/", SendEmailCodeView.as_view(),name='sendemail_code'),
    # 修改邮箱
    path("update_email/", UpdateEmailView.as_view(),name='update_email'),
    # 我的课程
    path("mycourse/", MyCourseView.as_view(),name='mycourse'),
    # 我的收藏--课程机构
    path('myfav/org/', MyFavOrgView.as_view(), name="myfav_org"),
    # 我的收藏--授课讲师
    path('myfav/teacher/', MyFavTeacherView.as_view(), name="myfav_teacher"),
    # 我的收藏--课程
    path('myfav/course/', MyFavCourseView.as_view(), name="myfav_course"),
    # 我的消息
    path('my_message/', MyMessageView.as_view(), name="my_message"),
]

Education_platform/apps/course/models.py
from django.db import models

# Create your models here.
# from django.utils.datetime_safe import datetime

from datetime import datetime

from oragnization.models import CourseOrg, Teacher


class Course(models.Model):
    """ 課程表 """

    # get_degree_display 通过html页面调取degree,可以返回对应的“初级”、“高级”
    DEGREE_CHOICES = (
        ("cj", "初级"),
        ("zj", "中级"),
        ("gj", "高级")
    )
    name = models.CharField("课程名", max_length=50)
    desc = models.CharField("课程描述", max_length=300)
    detail = models.TextField("课程详情")
    degree = models.CharField('难度', choices=DEGREE_CHOICES, max_length=2)
    learn_times = models.IntegerField("学习时长(分钟数)", default=0)
    students = models.IntegerField("学习人数", default=0, editable=False)
    fav_nums = models.IntegerField("收藏人数", default=0, editable=False)
    image = models.ImageField("封面图", upload_to="courses/%Y/%m", max_length=100, blank=True)
    click_nums = models.IntegerField("点击数", default=0, editable=False)
    add_time = models.DateTimeField("添加时间", default=datetime.now,)
    course_org = models.ForeignKey(CourseOrg, on_delete=models.CASCADE, verbose_name="所属机构", null=True, blank=True)
    category = models.CharField("课程类别", max_length=20, default="")
    tag = models.CharField('课程标签', default='', max_length=10)
    teacher = models.ForeignKey(Teacher, verbose_name='讲师', null=True, blank=True, on_delete=models.CASCADE)
    youneed_know = models.CharField('课程须知', max_length=300, default='')
    teacher_tell = models.CharField('老师告诉你', max_length=300, default='')
    is_banner = models.BooleanField('是否轮播', default=False)

    class Meta:
        verbose_name = "课程"
        verbose_name_plural = verbose_name

    def get_zj_nums(self):
        # 获取课程的章节数
        return self.lesson_set.all().count()

    def get_course_lesson(self):
        # 获取课程的章节
        return self.lesson_set.all()

    def get_learn_users(self):
        # 获取这门课程的学习用户
        return self.usercourse_set.all()[:5]

    def count_learn_users(self):
        return self.usercourse_set.all().count()

    def __str__(self):
        return self.name


class Lesson(models.Model):
    """ 章节信息表 """
    course = models.ForeignKey(Course, verbose_name='课程', on_delete=models.CASCADE)
    name = models.CharField("章节名", max_length=100)
    add_time = models.DateTimeField("添加时间", default=datetime.now)

    class Meta:
        verbose_name = "章节"
        verbose_name_plural = verbose_name

    def get_lesson_vedio(self):
        # 获取章节所有视频
        return self.video_set.all()

    def __str__(self):
        return '《{0}》课程的章节 >> {1}'.format(self.course, self.name)


class Video(models.Model):
    """视频"""
    lesson = models.ForeignKey(Lesson, verbose_name="章节", on_delete=models.CASCADE)
    name = models.CharField("视频名", max_length=100)
    url = models.CharField('访问地址', default='', max_length=200)
    learn_times = models.IntegerField("学习时长(分钟数)", default=0)
    add_time = models.DateTimeField("添加时间", default=datetime.now)

    class Meta:
        verbose_name = "视频"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class CourseResource(models.Model):
    """课程资源"""
    course = models.ForeignKey(Course, verbose_name="课程", on_delete=models.CASCADE)
    name = models.CharField("名称", max_length=100)
    download = models.FileField("资源文件", upload_to="course/resource/%Y/%m", max_length=100)
    add_time = models.DateTimeField("添加时间", default=datetime.now)

    class Meta:
        verbose_name = "课程资源"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

Education_platform/templates/course-comment.html
{% extends 'course-video.html' %}

{% load staticfiles %}
{% block title %}课程评论{% endblock %}
{% block custom_bread %}
    <section>
        <div class="wp">
            <ul class="crumbs">
                <li><a href="/">首页</a>></li>
                <li><a href="{% url 'course:course_list' %}">公开课程</a>></li>
                <li><a href="{% url 'course:course_detail' course.id %}">课程详情</a>></li>
                <li>课程评论</li>
            </ul>
        </div>
    </section>
{% endblock %}

{% block left_content %}
    <!--展示页切换-->
    <div class="mod-tab-menu">
        <ul class="course-menu clearfix">
            <li><a class="" id="learnOn"  href="{% url 'course:course_info' course.id %}"><span>章节</span></a></li>
            <li><a class="ui-tabs-active active" id="commentOn" href="{% url 'course:course_comments' course.id %}"><span>评论</span></a></li>
        </ul>
    </div>
    <!--发布评论-->
    <div id="js-pub-container" class="issques clearfix js-form">
        <div class="wgt-ipt-wrap pub-editor-wrap " id="js-pl-input-fake">
            <textarea id="js-pl-textarea" class="" placeholder="扯淡、吐槽、表扬、鼓励……想说啥就说啥！" ></textarea>
        </div>
        <input type="button" id="js-pl-submit" class="pub-btn" data-cid="452" value="发表评论">
        <p class="global-errortip js-global-error"></p>
    </div>
    <!--显示评论-->
    <div id="course_note">
        <ul class="mod-post" id="comment-list">
            {% for comment in all_comments %}
            <li class="post-row">
                <div class="media">
                    <span target="_blank"><img src='{{ MEDIA_URL }}{{ comment.user.image }}' width='40' height='40' /></span>
                </div>
                <div class="bd">
                    <div class="tit">
                        <span target="_blank">{{ comment.user.nick_name }}</span>
                    </div>
                    <p class="cnt">{{ comment.comments }}</p>
                    <div class="footer clearfix">
                        <span title="创建时间" class="l timeago">时间：{{ comment.add_time }}</span>
                    </div>
                </div>
            </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

{% block custom_js %}
    <!--添加评论-->
    <script type="text/javascript">
     $("#js-pl-submit").keydown(function(event){
        if(event.keyCode == 13){
             $('#js-pl-submit').trigger('click');
        }
    });

    $('#js-pl-submit').on('click', function(){
        var comments = $("#js-pl-textarea").val();
        if(comments == ""){
            alert("评论不能为空");
            return
        }
        $.ajax({
            cache: false,
            type: "POST",
            url:"{% url 'course:add_comment' %}",
            data:{'course_id':{{ course.id }}, 'comments':comments},
            async: true,
            beforeSend:function(xhr, settings){
            xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
            },
            success: function(data) {
                if(data.status == 'fail'){
                    if(data.msg == '用户未登录'){
                        window.location.href="login.html";
                    }else{
                        alert(data.msg)
                    }

                }else if(data.status == 'success'){
                    window.location.reload();//刷新当前页面.
                }
            },
        });
    });
</script>
{% endblock %}

Education_platform/templates/course-play.html
{% extends 'base.html' %}

{% block title %}
    {{ video.name }}
{% endblock %}
{% load staticfiles %}


{% block custom_bread %}
    <section>
        <div class="wp">
            <div class="crumbs">
                <ul>
                    <li><a href="{% url 'index' %}">首页</a>></li>
                    <li><a href="{% url 'course:course_list' %}">公开课程</a>></li>
                    <!-- 课程名-章节名-视频名 -->
                    <li><a href="{% url 'course:course_detail' course.id %}">{{ course.name }}-{{ video.lesson.name }}-{{ video.name }}</a>></li>
                    <li></li>
                </ul>
            </div>
        </div>
    </section>
{% endblock %}

{% block custom_css %}
    <!--<link href="https://unpkg.com/video.js/dist/video-js.css" rel="stylesheet" type="text/css">-->
    <link rel="stylesheet" type="text/css" href="//vjs.zencdn.net/7.2/video-js.min.css"/>
    <!--<link rel="stylesheet" type="text/css" href="{% static 'css/video-js.min.css' %}">-->
    <!--<link rel="stylesheet" type="text/css" href="mediaelementplayer.min.css"/>-->


    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/base.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/common-less.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/course/learn-less.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/mooc.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/course/common-less.css' %}">
    <style>
        .video-js .vjs-big-play-button {
            top: 50%;
            left: 50%;
        }
    </style>
{% endblock %}

{% block custom_js %}
    <!--<script src="{% static 'js/video.min.js' %}" type="text/javascript"></script>-->
    <script src="//vjs.zencdn.net/7.2/video.min.js" type="text/javascript"></script>
<!--<script src="https://unpkg.com/video.js/dist/video.js" type="text/javascript></script>-->
    <!--<script src="{% static 'js/jquery.js' %}" type="text/javascript"></script>-->
    <!--<script src="{% static 'js/mediaelement-and-player.min.js' %}" type="text/javascript"></script>-->


{% endblock %}

{% block content %}
    <div id="main">
        <div class="course-info-main clearfix w has-progress">
            <div style="width:1200px;height: 650px; margin-left:100px">
                <video class="video-js vjs-default-skin" controls="controls" preload="auto" height="600" width="1000"
                       poster="{% static 'images/echo-hereweare.jpg' %}"
                       data-setup="">
                    <!--<source src="{% static 'video/keepto.mp4' %}" type="video/mp4">-->
                    <source src="{{ video.url }}" type="video/mp4">

                </video>
            </div>
            <div class="info-bar clearfix">
                <div class="content-wrap clearfix">
                    <!--左侧功能区-->
                    <div class="content">
                        <!-- 章节+评论分页 -->
                        <div class="mod-tab-menu">
                            <ul class="course-menu clearfix">
                                <li><a class="ui-tabs-active active" id="learnOn"
                                       href="{% url 'course:course_info' course.id %}"><span>章节</span></a></li>
                                <li><a id="commentOn" class=""
                                       href="{% url 'course:course_comments' course.id %}"><span>评论</span></a></li>
                            </ul>
                        </div>
                        <!--课程公告+章节内容-->
                        <div id="notice" class="clearfix">
                            <div class="l"><strong>课程公告:</strong> <a
                                    href="javascript:void(0)">Spring的文档以及相关的jar文件已上传</a></div>
                        </div>

                        <div class="mod-chapters">
                            {% for lesson in course.lesson_set.get_queryset %}
                                <div class="chapter chapter-active">
                                    <h3>
                                        <strong><i class="state-expand"></i>{{ lesson.name }}</strong>
                                    </h3>
                                    <ul class="video">

                                        {% for video in lesson.video_set.get_queryset %}
                                            <li>
                                                <a target="_blank" href="{% url 'course:course_video' video.id %}"
                                                   class="J-media-item studyvideo">{{ video.name }}
                                                    ({{ video.learn_times }})
                                                    <i class="study-state"></i>
                                                </a>
                                            </li>
                                        {% endfor %}

                                    </ul>
                                </div>
                            {% endfor %}
                        </div>

                    </div>
                    <!--右侧功能区-->
                    <div class="aside r">
                        <div class="bd">

                            <div class="box mb40">
                                <h4>资料下载</h4>
                                <ul class="downlist">
                                    {% for course_resource in course.courseresource_set.get_queryset %}
                                        <li>
                                            <span><i
                                                    class="aui-iconfont aui-icon-file"></i>&nbsp;&nbsp;{{ course_resource.name }}</span>
                                            <a href="{{ MEDIA_URL }}{{ course_resource.download }}" class="downcode"
                                               target="_blank" download="" data-id="274" title="">下载</a>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </div>

                            <div class="box mb40">
                                <h4>讲师提示</h4>
                                <div class="teacher-info">
                                    <a href="{% url 'org:org_teacher' course.teacher.id %}" target="_blank">
                                        <img src='{{ MEDIA_URL }}{{ course.teacher.image }}' width='80' height='80'/>
                                    </a>
                                    <span class="tit">
          <a href="{% url 'org:org_teacher' course.teacher.id %}" target="_blank">{{ course.teacher.name }}</a>
        </span>
                                    <span class="job">{{ course.teacher.work_position }}</span>
                                </div>
                                <div class="course-info-tip">
                                    <dl class="first">
                                        <dt>课程须知</dt>
                                        <dd class="autowrap">{{ course.you_need_know }}</dd>
                                    </dl>
                                    <dl>
                                        <dt>老师告诉你能学到什么？</dt>
                                        <dd class="autowrap">{{ course.teacher_tell }}</dd>
                                    </dl>
                                </div>
                            </div>

                            <div class="cp-other-learned  js-comp-tabs">
                                <div class="cp-header clearfix">
                                    <h2 class="cp-tit l">该课的同学还学过</h2>
                                </div>
                                <div class="cp-body">
                                    <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="course"
                                         style="display: block">
                                        <!-- img 200 x 112 -->
                                        <ul class="other-list">

                                            {% for relate_course in relate_courses %}
                                                <li class="curr">
                                                    <a href="{% url 'course:course_detail' relate_course.id %}"
                                                       target="_blank">
                                                        <img src="{{ MEDIA_URL }}{{ relate_course.image }}"
                                                             alt="{{ relate_course.name }}">
                                                        <span class="name autowrap">{{ relate_course.name }}</span>
                                                    </a>
                                                </li>
                                            {% endfor %}

                                        </ul>
                                    </div>
                                    <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="plan">
                                        <ul class="other-list">

                                        </ul>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
                <div class="clear"></div>

            </div>

        </div>
    </div>
{% endblock %}

Education_platform/templates/course-video.html
{% extends 'base.html' %}

{% load staticfiles %}
{% block title %}章节信息{% endblock %}


{% block custom_bread %}
    <section>
        <div class="wp">
            <ul class="crumbs">
                <li><a href="/">首页</a>></li>
                <li><a href="{% url 'course:course_list' %}">公开课程</a>></li>
                <li><a href="{% url 'course:course_detail' course.id %}">课程详情</a>></li>
                <li>章节信息</li>
            </ul>
        </div>
    </section>
{% endblock %}

{% block custom_css %}
	<link rel="stylesheet" type="text/css" href="/static/css/muke/course/course-comment.css" />
    <link rel="stylesheet" type="text/css" href="/static/css/muke/base.css" />
    <link rel="stylesheet" type="text/css" href="/static/css/muke/common-less.css" />
    <link rel="stylesheet" type="text/css" href="/static/css/muke/course/learn-less.css" />
    <link rel="stylesheet" type="text/css" href="/static/css/aui.css" />
    <link rel="stylesheet" type="text/css" href="/static/css/mooc.css" />
    <link rel="stylesheet" type="text/css" href="/static/css/muke/course/common-less.css">
{% endblock %}

{% block content %}
    <div id="main">
    <div class="course-infos">
        <div class="w pr">
            <div style="height: 15px" class="path">
            </div>
            <div class="hd">
                <h2 class="l">&nbsp;&nbsp;{{ course.name }}</h2>
            </div>
            <div class="statics clearfix">
                <div class="static-item ">
                    <span class="meta">难度</span>
                    <span class="meta-value"><strong>{{ course.get_degree_display }}</strong></span>
                    <em></em>
                </div>
                <div class="static-item static-time">
                    <span class="meta">时长</span>
                    <span class="meta-value">{{ course.learn_times }}</span>
                    <em></em>
                </div>
                <div class="static-item">
                    <span class="meta">学习人数</span>
                    <span class="meta-value"><strong>{{ course.students }}</strong></span>
                    <em></em>
                </div>
            </div>
        </div>
    </div>
    <div class="course-info-main clearfix w has-progress">

        <div class="info-bar clearfix">
        <div class="content-wrap clearfix">
            <div class="content">
                {% block left_content %}
                <div class="mod-tab-menu">
                    <ul class="course-menu clearfix">
                        <li><a class="ui-tabs-active active" id="learnOn"  href="{% url 'course:course_info' course.id %}"><span>章节</span></a></li>
                        <li><a id="commentOn" class="" href="{% url 'course:course_comments' course.id %}"><span>评论</span></a></li>
                    </ul>
                </div>
                <div id="notice" class="clearfix">
                    <div class="l"> <strong>课程公告:</strong> <a  href="javascript:void(0)">Spring的文档以及相关的jar文件已上传</a> </div>
                </div>
                <div class="mod-chapters">
                    {% for lesson in course.get_course_lesson %}
                    <div class="chapter chapter-active" >
                        <h3>
                            <strong><i class="state-expand"></i>{{ lesson.name }}</strong>
                        </h3>
                        <ul class="video">
                            {% for vedio in lesson.get_lesson_vedio %}
                            <li>
                                <a target="_blank" href="{% url 'course:course_video' vedio.id %}" class="J-media-item studyvideo">{{ vedio.name }}({{ vedio.learn_times }})
                                    <i class="study-state"></i>
                                </a>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                    {% endfor %}
                </div>
                {% endblock %}
            </div>
            <!--右侧功能栏-->
            <div class="aside r">
                <div class="bd">
                    <div class="box mb40">
                        <h4>资料下载</h4>
                        <ul class="downlist">
                            {% for resource in all_resource %}
                            <li>
                                <span ><i class="aui-iconfont aui-icon-file"></i>{{ resource.name }}</span>
                                <a href="{{ MEDIA_URL }}{{ resource.download }}" class="downcode" target="_blank" download="" data-id="274" title="">下载</a>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="box mb40">
                        <h4>讲师提示</h4>
                        <div class="teacher-info">
                            <a href="/u/315464/courses?sort=publish" target="_blank">
                                <img src='{{ MEDIA_URL }}{{ course.teacher.image }}' width='80' height='80' />
                            </a>
                            <span class="tit">
                              <a href="/u/315464/courses?sort=publish" target="_blank">{{ course.teacher.name }}</a>
                            </span>
                            <span class="job">{{ course.teacher.work_position }}</span>
                        </div>
                        <div class="course-info-tip">
                            <dl class="first">
                                <dt>课程须知</dt>
                                <dd class="autowrap">{{ course.youneed_know }}</dd>
                            </dl>
                            <dl>
                                <dt>老师告诉你能学到什么？</dt>
                                <dd class="autowrap">{{ course.teacher_tell }}</dd>
                            </dl>
                        </div>
                    </div>
                    <div class="cp-other-learned  js-comp-tabs">
                        <div class="cp-header clearfix">
                            <h2 class="cp-tit l">该课的同学还学过</h2>
                        </div>
                        <div class="cp-body">
                            <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="course" style="display: block">
                                <!-- img 200 x 112 -->
                                <ul class="other-list">
                                    {% for relate_course in relate_courses %}
                                    <li class="curr">
                                        <a href="{% url 'course:course_detail' relate_course.id %}" target="_blank">
                                            <img src="{{ MEDIA_URL }}{{ relate_course.image }}" alt="django与vuejs实战项目2">
                                            <span class="name autowrap">{{ relate_course.name }}</span>
                                        </a>
                                    </li>
                                    {% endfor %}
                                </ul>
                            </div>
                            <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="plan">
                                <ul class="other-list">
                                    <li class="curr">
                                        <a href="/course/programdetail/pid/31?src=sug" target="_blank">
                                            <img src="http://img.mukewang.com/56551e6700018b0c09600720-240-135.jpg" alt="Java工程师">
                                            <span class="name autowrap">Java工程师</span>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="clear"></div>

    </div>

</div>
</div>
{% endblock %}

Education_platform/templates/usercenter-mycourse.html
{% extends 'user_base.html' %}
{% block title %}
    我的课程
{% endblock %}
{% block custom_bread %}
    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li><a href="/user/home/">个人中心</a>></li>
                <li>我的课程</li>
            </ul>
        </div>
    </section>
    {% endblock %}

{% block custom_right_content %}
    <div class="right" >
        <div class="personal_des Releasecont">
            <div class="head">
                <h1>我的课程</h1>
            </div>
        </div>
        <div class="personal_des permessage">
            <div class="companycenter">
                <div class="group_list brief">
                    {% for user_course in user_courses %}
                    <div class="module1_5 box">
                            <a href="{% url 'course:course_detail' user_course.course.id %}">
                                <img width="214" height="190" class="scrollLoading" src="{{ MEDIA_URL }}{{ user_course.course.image }}"/>
                            </a>
                            <div class="des">
                                <a href="course-detail.html"><h2>{{ user_course.course.name }}</h2></a>
                                <span class="fl">课时：<i class="key">{{ user_course.course.learn_times }}</i></span>
                                <span class="fr">学习人数：{{ user_course.course.students }}</span>
                            </div>
                            <div class="bottom">
                                <span class="fl">{{ user_course.course.course_org.name }}</span>
                                <span class="star fr  notlogin" data-favid="15">{{ user_course.course.fav_nums }}</span>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}